language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install pylint coverage coveralls
  - pip install -e .
script:
  - nosetests -s -q --with-coverage --cover-package=enocean
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - python: nightly

after_success:
  - pylint enocean -d line-too-long
  - coveralls
